### Register a new client
POST http://localhost:5010/client/
Content-Type: application/json

{
  "discordId": "discord123",
  "name": "second user"
}

### Get a client by id
GET http://localhost:5010/client/5aa86228-797a-4347-8e1b-be0e929cf76e

### Get client by discord ID
GET http://localhost:5010/client/discordId/testdiscorddid123

### Get all clients
GET http://localhost:5010/client/testdiscorddid123

### Update a client (partial update allowed)
PUT http://localhost:5010/client/5b04a69f-0d31-42fc-9f09-c0f6714539be
Content-Type: application/json

{
  "name": "Updated Name"
}

### Delete a client
DELETE http://localhost:5010/client/11111111-1111-1111-1111-111111111111
