services:

  economy-api:
    build: ./economy_api
    container_name: economy_api_container
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    networks:
      - chorume_network
    restart: unless-stopped

  chorume-bot:
    build: ./chorume_bot
    container_name: chorume_bot_container
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - ECONOMY_API_URL=http://economy-api:5000
      - ECONOMY_SERVICE_URL=http://economy-service:3000
    networks:
      - chorume_network
    depends_on:
      - economy-api
      - db-migration-service
    restart: unless-stopped

  postgres-db:
    image: postgres:14
    container_name: postgres_db_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-economyuser}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-economypass}
      - POSTGRES_DB=${DB_NAME:-economydb}
    volumes:
      - economy_data:/var/lib/postgresql/data
    networks:
      - chorume_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-economyuser} -d ${DB_NAME:-economydb}"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-migration-service:
    build: ./db_migration_service
    container_name: db_migration_service_container
    depends_on:
      - postgres-db
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_USER=${DB_USER:-economyuser}
      - DB_PASSWORD=${DB_PASSWORD:-economypass}
      - DB_NAME=${DB_NAME:-economydb}
    networks:
      - chorume_network
    volumes:
      - ./db_migration_service/src/migration:/app/src/migration

networks:
  chorume_network:
    driver: bridge

volumes:
  bet_data:
  economy_data:
