services:

  balance-api:
    build: ./balance_api
    container_name: balance_api_container
    ports:
      - "5001:5000"
    networks:
      - chorume_network
    env_file:
      - .env
    restart: unless-stopped

  coin-api:
    build: ./coin_api
    container_name: coin_api_container
    ports:
      - "5002:5000"
    networks:
      - chorume_network
    depends_on:
      - postgres-db
      - balance-api
      - client-api
    env_file:
      - .env
    restart: unless-stopped

  bet-api:
    build: ./bet_api
    container_name: bet_api_container
    ports:
      - "5003:5000"
    networks:
      - chorume_network
    depends_on:
      - balance-api
      - client-api
    environment:
      - BALANCE_API_URL=http://balance-api:5000
      - CLIENT_API_URL=http://client-api:5000
    env_file:
      - .env
    restart: unless-stopped

  client-api:
    build: ./client_api
    container_name: client_api_container
    ports:
      - "5000:5000"
    networks:
      - chorume_network
    depends_on:
      - postgres-db
    env_file:
      - .env
    restart: unless-stopped

  chorume-bot:
    build: ./chorume_bot
    container_name: chorume_bot_container
    networks:
      - chorume_network
    depends_on:
      - client-api
      - db-migration-service
      - balance-api
      - coin-api
      - bet-api
    environment:
      - BALANCE_API_URL=http://balance-api:5000
      - CLIENT_API_URL=http://client-api:5000
      - COIN_API_URL=http://coin-api:5000
      - BET_API_URL=http://bet-api:5000
    env_file:
      - .env
    restart: unless-stopped

  postgres-db:
    image: postgres:14
    container_name: postgres_db_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - economy_data:/var/lib/postgresql/data
    networks:
      - chorume_network
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-migration-service:
    build: ./db_migration_service
    container_name: db_migration_service_container
    depends_on:
      - postgres-db
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - chorume_network
    volumes:
      - ./db_migration_service/src/migration:/app/src/migration
    env_file:
      - .env

networks:
  chorume_network:
    driver: bridge

volumes:
  economy_data:
