services:

  balance-api:
    build: ./balance_api
    container_name: balance_api_container
    ports:
      - "5011:5000"
    networks:
      - buteco_network
    env_file:
      - .env
    restart: unless-stopped

  coin-api:
    build: ./coin_api
    container_name: coin_api_container
    ports:
      - "5012:5000"
    networks:
      - buteco_network
    depends_on:
      - postgres-db
      - balance-api
      - client-api
    env_file:
      - .env
    restart: unless-stopped

  bet-api:
    build: ./bet_api
    container_name: bet_api_container
    ports:
      - "5013:5000"
    networks:
      - buteco_network
    depends_on:
      - balance-api
      - client-api
    env_file:
      - .env
    restart: unless-stopped

  client-api:
    build: ./client_api
    container_name: client_api_container2
    ports:
      - "5010:5000"
    networks:
      - buteco_network
    depends_on:
      - postgres-db
    env_file:
      - .env
    restart: unless-stopped

  buteco-bot:
    build: ./buteco_bot
    container_name: buteco_bot_container
    networks:
      - buteco_network
    depends_on:
      - client-api
      - db-migration-service
      - balance-api
      - coin-api
      - bet-api
    env_file:
      - .env
    restart: unless-stopped

  postgres-db:
    image: postgres:14
    container_name: postgres_db_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - economy_data:/var/lib/postgresql/data
    networks:
      - buteco_network
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-migration-service:
    build: ./db_migration_service
    container_name: db_migration_service_container
    depends_on:
      - postgres-db
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - buteco_network
    volumes:
      - ./db_migration_service/src/migration:/app/src/migration
    env_file:
      - .env

  genai-api:
    build: ./genai_api
    container_name: genai_api_container
    ports:
      - "5014:5000"
    networks:
      - buteco_network
    depends_on:
      - postgres-db
    env_file:
      - .env
    restart: unless-stopped

networks:
  buteco_network:
    driver: bridge

volumes: 
  economy_data:
